
FROM node:20-slim

# habilita pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# define ambiente como DEV
ENV NODE_ENV=development

WORKDIR /app

# copie apenas o necessário primeiro (melhor cache)
COPY package.json pnpm-lock.yaml ./


# instala dependências + devDependencies
RUN pnpm install

# copia todo resto
COPY . .

EXPOSE 3333


CMD sh -c "pnpm drizzle-kit migrate && pnpm dev"
